### ISSUE TITLE
Android upload is excessively slow because uploadPacketDelay is set to 400ms.

### ISSUE THREAD

**Issue by corecode** [juliansteenbakker/nordic_dfu#64]
https://github.com/juliansteenbakker/nordic_dfu/blob/master/android/src/main/kotlin/dev/steenbakker/nordicdfu/NordicDfuPlugin.kt#L120 unconditionally sets 400ms inter-packet delay, which severely slows down the firmware upload.  Please remove or allow configuration.

**Comment by aabdulat1998** [comment]
Would it be possible to manually go in there and change it?

**Comment by corecode** [comment]
That's what I did in my fork.

**Comment by corecode** [comment]
Looks like it was fixed: <https://github.com/juliansteenbakker/nordic_dfu/blob/7b97b63f5cc52883dd962e29645cc7e6d6aad098/lib/src/android_special_paramter.dart#L57>.  Just set this value to 0 and it should be much faster.

Thanks @juliansteenbakker!

**Comment by letisoft** [comment]
Hello,

I have updated to 5.2.1 but AndroidSpecialParameter still has no delay parameter? am I doing something wrong or fix is not yet in an official release?

Thank you very much!
V
