### ISSUE TITLE
I can't use it on IOS

### ISSUE THREAD

**Issue by CGuoJunLi** [juliansteenbakker/nordic_dfu#67]
This is my platform information:
flutter:3.0.5
XCODE 13.41
ios: IPhone 12 mini  (15.5)

It seems to be connected in a loop all the time,like this:

flutter: onDeviceConnecting:FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onDfuProcessStarting：FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onEnablingDfuMode：FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onDeviceConnecting:FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onDfuProcessStarting：FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onEnablingDfuMode：FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onDeviceConnecting:FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onDfuProcessStarting：FD3E9841-5843-7AFE-9DB1-F83E88479A42
flutter: onEnablingDfuMode：FD3E9841-5843-7AFE-9DB1-F83E88479A42

this my code:
 await NordicDfu().startDfu(
        "FD3E9841-5843-7AFE-9DB1-F83E88479A42", _localPath + '/mcbin.zip',
        fileInAsset: false,
        iosSpecialParameter:
            IosSpecialParameter(alternativeAdvertisingNameEnabled: true),
        onProgressChanged: (
      deviceAddress,
      percent,
      speed,
      avgSpeed,
      currentPart,
      partsTotal,
    ) async {
      debugPrint('deviceAddress: $deviceAddress, percent: $percent');

      sendvalue = percent;
      if (sendvalue == 100) {
        await Future.delayed(const Duration(seconds: 3));
        Navigator.pop(context, true);
      }
    }, onDeviceConnected: ((str) {
      print("onDeviceConnected:" + str);
    }), onDeviceConnecting: ((str) {
      print("onDeviceConnecting:" + str);
    }), onDeviceDisconnected: ((str) {
      print("onDeviceDisconnected:" + str);
    }), onDeviceDisconnecting: ((str) {
      print("onDeviceDisconnecting:" + str);
    }), onDfuAborted: ((str) {
      print("onDfuAborted:"+str);
    }), onDfuCompleted: ((str) {
      print("onDfuCompleted:" + str);
    }), onDfuProcessStarted: ((str) {
      print("onDfuProcessStarted" + str);
    }), onDfuProcessStarting: ((str) {
      print("onDfuProcessStarting：" + str);
    }), onEnablingDfuMode: ((str) {
      print("onEnablingDfuMode：" + str);
    }), onFirmwareValidating: ((str) {
      print("onFirmwareValidating：" + str);
    }), onError: ((address, error, errorType, message) {
      print(address);
      print(error);
      print(errorType);
      print(message);
    }));

What should I do now?

**Comment by juliansteenbakker** [comment]
I'm sorry for the late response, but it seems like this is a problem with the underlying framework rather than this flutter plugin. Please check https://github.com/NordicSemiconductor/Android-DFU-Library for android framework and https://github.com/NordicSemiconductor/IOS-DFU-Library for ios framework.
